version: 2
jobs:
  build:
    working_directory: /dockerapp-demo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp-demo python test.py
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp-demo_dockerapp-demo $DOCKER_HUB_USER_ID/dockerapp-demo:$CIRCLE_SHA1
            docker tag dockerapp-demo_dockerapp-demo $DOCKER_HUB_USER_ID/dockerapp-demo:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp-demo:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp-demo:latest
